force-app/main/default/objects/Scoring_Event_Submission__c/Scoring_Event_Submission__c.object-meta.xml
<CustomObject>
    <label>Scoring Event Submission</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scoring Event Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Scoring_Event_Submission__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Scoring_Event_Submission__c/fields/Submission_Score__c.field-meta.xml
<CustomField>
    <fullName>Submission_Score__c</fullName>
    <label>Submission Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SubmissionTriggerHandlerTest.cls
@isTest
private class SubmissionTriggerHandlerTest {
    @testSetup static void dataSetup(){
        ScoringDataFactory.createBasicScoringData();
    }

    @isTest static void testSubmissionTriggerHandler_UpdateApprove() {
        try {
            Test.startTest();
            Scoring_Event_Submission__c sub = [SELECT Id, Approval_Status__c FROM Scoring_Event_Submission__c LIMIT 1];
            sub.Approval_Status__c = 'Approved';
            update sub;
            Test.stopTest();
        } catch (Exception ex) {
            
        } finally {
            List<Scoring_Event_Submission__c> subs = [SELECT Id, Submission_Score__c FROM Scoring_Event_Submission__c WHERE Submission_Score__c > 0];
            Assert.areEqual(subs.size(), 1, 'The submission score is updated.');
        }
    }
}