force-app/main/default/objects/Scoring_Event__c/Scoring_Event__c.object-meta.xml
<CustomObject>
    <label>Scoring Event</label>
    <nameField>
        <label>Scoring Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scoring Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Scoring_Event_Clue__c/Scoring_Event_Clue__c.object-meta.xml
<CustomObject>
    <label>Scoring Event Clue</label>
    <nameField>
        <displayFormat>CLUE-{0000}</displayFormat>
        <label>Scoring Event Clue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scoring Event Clues</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Scoring_Event_Clue__c/fields/Event_Location__c.field-meta.xml
<CustomField>
    <fullName>Event_Location__c</fullName>
    <label>Event Location</label>
    <referenceTo>Scoring_Event_Location__c</referenceTo>
    <relationshipLabel>Event Clues</relationshipLabel>
    <relationshipName>Scoring_Event_Clues</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Scoring_Event_Clue__c/fields/Max_Point__c.field-meta.xml
<CustomField>
    <fullName>Max_Point__c</fullName>
    <label>Max Point</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Scoring_Event_Clue__c/fields/Min_Point__c.field-meta.xml
<CustomField>
    <fullName>Min_Point__c</fullName>
    <label>Min Point</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Scoring_Event_Clue__c/fields/Reduction_Step_Point__c.field-meta.xml
<CustomField>
    <fullName>Reduction_Step_Point__c</fullName>
    <label>Reduction Step Point</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Scoring_Event_Clue__c/fields/Scoring_Event__c.field-meta.xml
<CustomField>
    <fullName>Scoring_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Scoring Event</label>
    <referenceTo>Scoring_Event__c</referenceTo>
    <relationshipLabel>Scoring Event Clues</relationshipLabel>
    <relationshipName>Scoring_Event_Clues</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Scoring_Event_Location__c/Scoring_Event_Location__c.object-meta.xml
<CustomObject>
    <label>Scoring Event Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scoring Event Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Scoring_Event_Location__c/fields/Scoring_Event__c.field-meta.xml
<CustomField>
    <fullName>Scoring_Event__c</fullName>
    <label>Scoring Event</label>
    <referenceTo>Scoring_Event__c</referenceTo>
    <relationshipLabel>Event Locations</relationshipLabel>
    <relationshipName>Scoring_Event_Locations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Scoring_Event_Submission__c/Scoring_Event_Submission__c.object-meta.xml
<CustomObject>
    <label>Scoring Event Submission</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scoring Event Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Scoring_Event_Submission__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Scoring_Event_Submission__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Scoring_Event_Location__c</referenceTo>
    <relationshipLabel>Submissions</relationshipLabel>
    <relationshipName>Submissions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Scoring_Event_Submission__c/fields/Scoring_Event__c.field-meta.xml
<CustomField>
    <fullName>Scoring_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Scoring_Event__c</referenceTo>
    <relationshipLabel>Submissions</relationshipLabel>
    <relationshipName>Scoring_Event_Submissions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Scoring_Event_Submission__c/fields/Scoring_Event_Clue__c.field-meta.xml
<CustomField>
    <fullName>Scoring_Event_Clue__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Scoring Event Clue</label>
    <referenceTo>Scoring_Event_Clue__c</referenceTo>
    <relationshipLabel>Scoring Event Submissions</relationshipLabel>
    <relationshipName>Scoring_Event_Submissions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Scoring_Event_Submission__c/fields/Scoring_Event_Team__c.field-meta.xml
<CustomField>
    <fullName>Scoring_Event_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team</label>
    <referenceTo>Scoring_Event_Team__c</referenceTo>
    <relationshipLabel>Submissions</relationshipLabel>
    <relationshipName>Scoring_Event_Submissions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Scoring_Event_Submission__c/fields/Scoring_Team__c.field-meta.xml
<CustomField>
    <fullName>Scoring_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Scoring Team</label>
    <referenceTo>Scoring_Team__c</referenceTo>
    <relationshipLabel>Scoring Event Submissions</relationshipLabel>
    <relationshipName>Scoring_Event_Submissions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Scoring_Event_Submission__c/fields/Submission_Score__c.field-meta.xml
<CustomField>
    <fullName>Submission_Score__c</fullName>
    <label>Submission Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Scoring_Event_Team__c/Scoring_Event_Team__c.object-meta.xml
<CustomObject>
    <label>Scoring Event Team</label>
    <nameField>
        <label>Scoring Event Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scoring Event Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Scoring_Event_Team__c/fields/Scoring_Event__c.field-meta.xml
<CustomField>
    <fullName>Scoring_Event__c</fullName>
    <label>Event</label>
    <referenceTo>Scoring_Event__c</referenceTo>
    <relationshipLabel>Event Teams</relationshipLabel>
    <relationshipName>Scoring_Event_Teams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Scoring_Event_Team__c/fields/Scoring_Event_Location__c.field-meta.xml
<CustomField>
    <fullName>Scoring_Event_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Scoring_Event_Location__c</referenceTo>
    <relationshipLabel>Teams</relationshipLabel>
    <relationshipName>Scoring_Event_Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Scoring_Event_Team__c/fields/Scoring_Team__c.field-meta.xml
<CustomField>
    <fullName>Scoring_Team__c</fullName>
    <label>Team</label>
    <referenceTo>Scoring_Team__c</referenceTo>
    <relationshipLabel>Teams</relationshipLabel>
    <relationshipName>Scoring_Event_Teams</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Scoring_Team__c/Scoring_Team__c.object-meta.xml
<CustomObject>
    <label>Scoring Team</label>
    <nameField>
        <label>Scoring Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scoring Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Scoring_Team_Member__c/Scoring_Team_Member__c.object-meta.xml
<CustomObject>
    <label>Scoring Team Member</label>
    <nameField>
        <displayFormat>TM-{0000}</displayFormat>
        <label>Team Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scoring Team Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Scoring_Team_Member__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team</label>
    <referenceTo>Scoring_Team__c</referenceTo>
    <relationshipLabel>Members</relationshipLabel>
    <relationshipName>Scoring_Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Scoring_Team_Member__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Scoring Team Members</relationshipLabel>
    <relationshipName>Scoring_Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SubmissionTriggerHandler.cls
public class SubmissionTriggerHandler {
    public static void beforeInsert(List<Scoring_Event_Submission__c> newSubs) {
        updateLookupSubmission(newSubs);
    }

    public static void beforeUpdate(Map<Id, Scoring_Event_Submission__c> oldSubs, List<Scoring_Event_Submission__c> newSubs) {
        updateLookupSubmission(newSubs);
        updateApprovedScoring(oldSubs, newSubs);
    }

    //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    public static void updateLookupSubmission(List<Scoring_Event_Submission__c> newSubs) {
        List<Scoring_Event_Submission__c> hasClueSubs = new List<Scoring_Event_Submission__c>();
        for (Scoring_Event_Submission__c newSub : newSubs) {
            if (newSub.Scoring_Event_Clue__c != null) {
                hasClueSubs.add(newSub);
            }
        }
        updateLookupSubmission_Clue(hasClueSubs);
    }
    
    public static void updateLookupSubmission_Clue(List<Scoring_Event_Submission__c> subs) {
        List<Scoring_Team_Member__c> teamMembers = [SELECT Id, Team__c FROM Scoring_Team_Member__c WHERE User__c = :UserInfo.getUserId()];
        if (teamMembers.size() == 0) return;
        Set<Id> teamIds = new Set<Id>();
        for (Scoring_Team_Member__c teamMember : teamMembers) {
            teamIds.add(teamMember.Team__c);
        }

        Set<Id> clueIds = new Set<Id>();
        for (Scoring_Event_Submission__c sub : subs) {
            clueIds.add(sub.Scoring_Event_Clue__c);
        }
        Map<Id, Scoring_Event_Clue__c> clues = new Map<Id, Scoring_Event_Clue__c>([
            SELECT Id, Event_Location__c, Event_Location__r.Scoring_Event__c 
            FROM Scoring_Event_Clue__c WHERE Id IN :clueIds
        ]);
        Set<Id> eventIds = new Set<Id>();
        for (Scoring_Event_Clue__c clue : clues.values()) {
            eventIds.add(clue.Event_Location__r.Scoring_Event__c);
        }
        Map<Id, Scoring_Event__c> events = new Map<Id, Scoring_Event__c>([
            SELECT Id, (SELECT Scoring_Team__c FROM Scoring_Event_Teams__r) 
            FROM Scoring_Event__c WHERE Id IN :eventIds
        ]);
        for (Scoring_Event_Submission__c sub : subs) {
            Scoring_Event_Clue__c clue = clues.get(sub.Scoring_Event_Clue__c);
            Scoring_Event__c event = events.get(clue.Event_Location__r.Scoring_Event__c);
            if (event.Scoring_Event_Teams__r == null) continue;
            for (Scoring_Event_Team__c eventTeam : event.Scoring_Event_Teams__r) {
                if (teamIds.contains(eventTeam.Scoring_Team__c)) {
                    sub.Scoring_Event_Team__c = eventTeam.Id;
                    sub.Scoring_Team__c = eventTeam.Scoring_Team__c;
                    continue;
                }
            }
            sub.Location__c = clue.Event_Location__c;
            sub.Scoring_Event__c = event.Id;
        } 
    }   

    public static void updateApprovedScoring(Map<Id, Scoring_Event_Submission__c> oldSubs, List<Scoring_Event_Submission__c> newSubs) {
        List<Id> recordIds = new List<Id>();
        List<Scoring_Event_Submission__c> curAppSubs = new List<Scoring_Event_Submission__c>();
        for (Scoring_Event_Submission__c newSub : newSubs) {
            Scoring_Event_Submission__c oldSub  = oldSubs.get(newSub.Id);
            if (newSub.Approval_Status__c == 'Approved' && newSub.Approval_Status__c != oldSub.Approval_Status__c) {
                recordIds.add(newSub.Scoring_Event_Clue__c);
                curAppSubs.add(newSub);
            }
        }

        List<Scoring_Event_Submission__c> calcSubs = calcSubmissionScoring(curAppSubs, recordIds, false);

        updateTriggerSub(newSubs, new Map<Id,Scoring_Event_Submission__c>(calcSubs));
    }

    public static void updateTriggerSub(List<Scoring_Event_Submission__c> newSubs, Map<Id,Scoring_Event_Submission__c> calcSubs) {
        for (Scoring_Event_Submission__c newSub : newSubs) {
            if (calcSubs.containsKey(newSub.Id)) {
                newSub.Submission_Score__c = calcSubs.get(newSub.Id).Submission_Score__c;
                calcSubs.remove(newSub.Id);
            }
        }
        update calcSubs.values();
    }
    
    public static List<Scoring_Event_Submission__c> calcSubmissionScoring(List<Scoring_Event_Submission__c> curAppSubs, List<Id> recordIds, Boolean isUpdate) {
        List<Scoring_Event_Submission__c> updSubmissions = new List<Scoring_Event_Submission__c>();
        Map<Id, Scoring_Event_Clue__c> clues = new Map<Id, Scoring_Event_Clue__c>(
            [SELECT Id, Max_Point__c, Min_Point__c, Reduction_Step_Point__c 
            FROM Scoring_Event_Clue__c WHERE Id IN :recordIds]);
        List<Scoring_Event_Submission__c> subs = [SELECT Id, Scoring_Event_Clue__c, Scoring_Event_Team__c, 
                                                    Submission_Score__c, CreatedDate
                                                FROM Scoring_Event_Submission__c 
                                                WHERE Scoring_Event_Clue__c IN :recordIds 
                                                    AND Approval_Status__c = 'Approved'
                                                    AND Scoring_Event_Team__c != null
                                                ORDER BY CreatedDate ASC];
        curAppSubs.addAll(subs);
        
        Map<Id, Map<Id, Scoring_Event_Submission__c>> calcSubs = new Map<Id, Map<Id, Scoring_Event_Submission__c>>();
        for (Scoring_Event_Submission__c sub : curAppSubs) {
            if (!calcSubs.containsKey(sub.Scoring_Event_Clue__c)) {
                calcSubs.put(sub.Scoring_Event_Clue__c, new Map<Id, Scoring_Event_Submission__c>());
            }
            if (calcSubs.get(sub.Scoring_Event_Clue__c).containsKey(sub.Scoring_Event_Team__c)) {
                Scoring_Event_Submission__c newSub = calcSubs.get(sub.Scoring_Event_Clue__c).get(sub.Scoring_Event_Team__c);
                newSub.Submission_Score__c = 0;
                updSubmissions.add(newSub);
            }
            calcSubs.get(sub.Scoring_Event_Clue__c).put(sub.Scoring_Event_Team__c, sub);
        }
        
        for(Id clueId : calcSubs.keySet()) {
            List<Scoring_Event_Submission__c> calcSub = calcSubs.get(clueId).values();
            calcClueSubmissionScoring(calcSub, clues.get(clueId));
            updSubmissions.addAll(calcSub);
        }
        if (isUpdate) update updSubmissions;
        return updSubmissions;
    }

    public static void calcClueSubmissionScoring(List<Scoring_Event_Submission__c> subs, Scoring_Event_Clue__c clue) {
        Decimal currentPoint = clue.Max_Point__c;
        for (Scoring_Event_Submission__c sub : subs) {
            sub.Submission_Score__c = currentPoint;
            currentPoint = currentPoint - clue.Reduction_Step_Point__c;
            if (currentPoint < clue.Min_Point__c) {
                currentPoint = clue.Min_Point__c;
            }
        }
    }
}