force-app/main/default/objects/Scoring_Event__c/Scoring_Event__c.object-meta.xml
<CustomObject>
    <label>Scoring Event</label>
    <nameField>
        <label>Scoring Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scoring Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Scoring_Event_Team__c/Scoring_Event_Team__c.object-meta.xml
<CustomObject>
    <label>Scoring Event Team</label>
    <nameField>
        <label>Scoring Event Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scoring Event Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Scoring_Event_Team__c/fields/Event_Team_Scoring__c.field-meta.xml
<CustomField>
    <fullName>Event_Team_Scoring__c</fullName>
    <label>Scoring</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Scoring_Event_Team__c/fields/Scoring_Event__c.field-meta.xml
<CustomField>
    <fullName>Scoring_Event__c</fullName>
    <label>Event</label>
    <referenceTo>Scoring_Event__c</referenceTo>
    <relationshipLabel>Event Teams</relationshipLabel>
    <relationshipName>Scoring_Event_Teams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Scoring_Event_Team__c/fields/Scoring_Team__c.field-meta.xml
<CustomField>
    <fullName>Scoring_Team__c</fullName>
    <label>Team</label>
    <referenceTo>Scoring_Team__c</referenceTo>
    <relationshipLabel>Teams</relationshipLabel>
    <relationshipName>Scoring_Event_Teams</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Scoring_Team__c/Scoring_Team__c.object-meta.xml
<CustomObject>
    <label>Scoring Team</label>
    <nameField>
        <label>Scoring Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scoring Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/LeadingTeamController.cls
public with sharing class LeadingTeamController {
    @AuraEnabled
    public static Scoring_Event_Team__c findLeadingTeam(String recordId) {
        List<Scoring_Event_Team__c> teams = [SELECT Id, Event_Team_Scoring__c, Scoring_Team__r.Name FROM Scoring_Event_Team__c 
            WHERE Scoring_Event__c = :recordId AND Event_Team_Scoring__c > 0 ORDER BY Event_Team_Scoring__c DESC];
        if (teams.size() > 0) return teams[0];
        return null;
    }
}