force-app/main/default/objects/Scoring_Event__c/Scoring_Event__c.object-meta.xml
<CustomObject>
    <label>Scoring Event</label>
    <nameField>
        <label>Scoring Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scoring Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Scoring_Event_Submission__c/Scoring_Event_Submission__c.object-meta.xml
<CustomObject>
    <label>Scoring Event Submission</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scoring Event Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Scoring_Event_Submission__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Scoring_Event_Submission__c/fields/Scoring_Event__c.field-meta.xml
<CustomField>
    <fullName>Scoring_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Scoring_Event__c</referenceTo>
    <relationshipLabel>Submissions</relationshipLabel>
    <relationshipName>Scoring_Event_Submissions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Scoring_Event_Submission__c/fields/Scoring_Event_Team__c.field-meta.xml
<CustomField>
    <fullName>Scoring_Event_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team</label>
    <referenceTo>Scoring_Event_Team__c</referenceTo>
    <relationshipLabel>Submissions</relationshipLabel>
    <relationshipName>Scoring_Event_Submissions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Scoring_Event_Team__c/Scoring_Event_Team__c.object-meta.xml
<CustomObject>
    <label>Scoring Event Team</label>
    <nameField>
        <label>Scoring Event Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scoring Event Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Scoring_Event_Team__c/fields/Scoring_Event__c.field-meta.xml
<CustomField>
    <fullName>Scoring_Event__c</fullName>
    <label>Event</label>
    <referenceTo>Scoring_Event__c</referenceTo>
    <relationshipLabel>Event Teams</relationshipLabel>
    <relationshipName>Scoring_Event_Teams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/LeadingTeamControllerTest.cls
@isTest
private class LeadingTeamControllerTest {

    @testSetup static void setup() {
        // Create test data for Scoring_Event_Team__c object
        ScoringDataFactory.createBasicScoringData();
    }

    @isTest static void testFindLeadingTeam() {
        Test.startTest();
        Scoring_Event_Submission__c sub = [SELECT Id, Approval_Status__c FROM Scoring_Event_Submission__c LIMIT 1];
        sub.Approval_Status__c = 'Approved';
        List<Scoring_Event__c> events = [SELECT Id FROM Scoring_Event__c];
        Scoring_Event_Team__c result = LeadingTeamController.findLeadingTeam(events.get(0).Id);
        Test.stopTest();
    }
}