force-app/main/default/objects/Scoring_Event__c/Scoring_Event__c.object-meta.xml
<CustomObject>
    <label>Scoring Event</label>
    <nameField>
        <label>Scoring Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scoring Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Scoring_Event__c/fields/Scoring_Start__c.field-meta.xml
<CustomField>
    <fullName>Scoring_Start__c</fullName>
    <label>Scoring Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Scoring_Event_Clue__c/Scoring_Event_Clue__c.object-meta.xml
<CustomObject>
    <label>Scoring Event Clue</label>
    <nameField>
        <displayFormat>CLUE-{0000}</displayFormat>
        <label>Scoring Event Clue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scoring Event Clues</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Scoring_Event_Clue__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Scoring_Event_Clue__c/fields/Event_Location__c.field-meta.xml
<CustomField>
    <fullName>Event_Location__c</fullName>
    <label>Event Location</label>
    <referenceTo>Scoring_Event_Location__c</referenceTo>
    <relationshipLabel>Event Clues</relationshipLabel>
    <relationshipName>Scoring_Event_Clues</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Scoring_Event_Clue__c/fields/Max_Point__c.field-meta.xml
<CustomField>
    <fullName>Max_Point__c</fullName>
    <label>Max Point</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Scoring_Event_Clue__c/fields/Scoring_Event__c.field-meta.xml
<CustomField>
    <fullName>Scoring_Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Scoring Event</label>
    <referenceTo>Scoring_Event__c</referenceTo>
    <relationshipLabel>Scoring Event Clues</relationshipLabel>
    <relationshipName>Scoring_Event_Clues</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Scoring_Event_Location__c/Scoring_Event_Location__c.object-meta.xml
<CustomObject>
    <label>Scoring Event Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scoring Event Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Scoring_Event_Location__c/fields/Scoring_Event__c.field-meta.xml
<CustomField>
    <fullName>Scoring_Event__c</fullName>
    <label>Scoring Event</label>
    <referenceTo>Scoring_Event__c</referenceTo>
    <relationshipLabel>Event Locations</relationshipLabel>
    <relationshipName>Scoring_Event_Locations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Scoring_Event_Team__c/Scoring_Event_Team__c.object-meta.xml
<CustomObject>
    <label>Scoring Event Team</label>
    <nameField>
        <label>Scoring Event Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scoring Event Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Scoring_Event_Team__c/fields/Event_Team_Scoring__c.field-meta.xml
<CustomField>
    <fullName>Event_Team_Scoring__c</fullName>
    <label>Scoring</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Scoring_Event_Team__c/fields/Scoring_Event__c.field-meta.xml
<CustomField>
    <fullName>Scoring_Event__c</fullName>
    <label>Event</label>
    <referenceTo>Scoring_Event__c</referenceTo>
    <relationshipLabel>Event Teams</relationshipLabel>
    <relationshipName>Scoring_Event_Teams</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Scoring_Event_Team__c/fields/Scoring_Event_Location__c.field-meta.xml
<CustomField>
    <fullName>Scoring_Event_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Scoring_Event_Location__c</referenceTo>
    <relationshipLabel>Teams</relationshipLabel>
    <relationshipName>Scoring_Event_Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Scoring_Event_Team__c/fields/Scoring_Team__c.field-meta.xml
<CustomField>
    <fullName>Scoring_Team__c</fullName>
    <label>Team</label>
    <referenceTo>Scoring_Team__c</referenceTo>
    <relationshipLabel>Teams</relationshipLabel>
    <relationshipName>Scoring_Event_Teams</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Scoring_Team__c/Scoring_Team__c.object-meta.xml
<CustomObject>
    <label>Scoring Team</label>
    <nameField>
        <label>Scoring Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scoring Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Scoring_Team_Member__c/Scoring_Team_Member__c.object-meta.xml
<CustomObject>
    <label>Scoring Team Member</label>
    <nameField>
        <displayFormat>TM-{0000}</displayFormat>
        <label>Team Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scoring Team Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Scoring_Team_Member__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team</label>
    <referenceTo>Scoring_Team__c</referenceTo>
    <relationshipLabel>Members</relationshipLabel>
    <relationshipName>Scoring_Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Scoring_Team_Member__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Scoring Team Members</relationshipLabel>
    <relationshipName>Scoring_Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ScoringAppLWCController.cls
public with sharing class ScoringAppLWCController {
    @AuraEnabled(cacheable=true)
    public static Scoring_Event_Team__c findLeadingTeam(String eventId) {
        List<Scoring_Event_Team__c> teams = [SELECT Id, Event_Team_Scoring__c, Scoring_Team__r.Name FROM Scoring_Event_Team__c 
            WHERE Scoring_Event__c = :eventId AND Event_Team_Scoring__c > 0 ORDER BY Event_Team_Scoring__c DESC];
        if (teams.size() > 0) return teams[0];
        return null;
    }

    @AuraEnabled
    public static List<Scoring_Team_Member__c> findJoinedEvent(String eventId) {
        List<Scoring_Event_Team__c> eventTeams = findTeams(eventId);
        Set<Id> teamIds = new Set<Id>();
        for (Scoring_Event_Team__c eventTeam : eventTeams) {
            teamIds.add(eventTeam.Scoring_Team__c);
        }
        List<Scoring_Team_Member__c> teamMembers = [SELECT Id, Team__c, Team__r.Name FROM Scoring_Team_Member__c WHERE Team__c IN :teamIds AND User__c = :UserInfo.getUserId()];
        return teamMembers;
    }

    @AuraEnabled
    public static List<Scoring_Event_Team__c> findTeams(String eventId) {
        return [SELECT Id, Scoring_Team__c, Scoring_Event_Location__c, Scoring_Team__r.Name FROM Scoring_Event_Team__c WHERE Scoring_Event__c = :eventId];
    }

    @AuraEnabled
    public static void saveTeamMember(String teamId, Boolean isJoin) {
        if (isJoin) {
            Scoring_Team_Member__c teamMember = new Scoring_Team_Member__c(
                Team__c = teamId,
                User__c = UserInfo.getUserId()
            );
            insert teamMember;
        } else {
            delete [SELECT Id FROM Scoring_Team_Member__c WHERE Team__c = :teamId AND User__c = :UserInfo.getUserId()];
        }
    }

    @AuraEnabled
    public static List<String> findJoinedLocationIds(String eventId) {
        List<Scoring_Event_Team__c> eventTeams = findTeams(eventId);
        Map<Id, Scoring_Event_Team__c> mapIdTeams = new Map<Id, Scoring_Event_Team__c>();
        for (Scoring_Event_Team__c eventTeam : eventTeams) {
            mapIdTeams.put(eventTeam.Scoring_Team__c, eventTeam);
        }
        List<Scoring_Team_Member__c> teamMembers = [SELECT Id, Team__c, Team__r.Name FROM Scoring_Team_Member__c WHERE Team__c IN :mapIdTeams.keySet() AND User__c = :UserInfo.getUserId()];
        List<String> locationIds = new List<String>();
        for (Scoring_Team_Member__c teamMember : teamMembers) {
            locationIds.add(mapIdTeams.get(teamMember.Team__c).Scoring_Event_Location__c);
        }
        return locationIds;
    }

    @AuraEnabled(cacheable=true)
    public static List<Scoring_Event_Clue__c> findClues(String recordId) {
        List<Scoring_Event_Clue__c> clues = new List<Scoring_Event_Clue__c>();
        Id tempId = Id.valueOf(recordId);
        if (tempId.getSobjectType() == Schema.Scoring_Event__c.getSObjectType()) {
            if (!Scoring_Event_Clue__c.getSobjectType().getDescribe().isCreateable()) {
                Scoring_Event__c evt = [SELECT Id, Scoring_Start__c FROM Scoring_Event__c WHERE Id = :recordId LIMIT 1];
                if (evt.Scoring_Start__c < Datetime.now()) {
                    return new List<Scoring_Event_Clue__c>();
                }
                List<String> locationIds = findJoinedLocationIds(recordId);
                clues = [SELECT Id, Description__c, Max_Point__c FROM Scoring_Event_Clue__c WHERE Event_Location__c IN :locationIds];
            }else {
                clues = [SELECT Id, Description__c, Max_Point__c FROM Scoring_Event_Clue__c WHERE Scoring_Event__c = :recordId];
            } 
        }
        return clues;
    }
}